#pragma once
#include <cstdint>

enum eProtocolPacketAck : std::uint16_t {
    UNKNOWN_ACK,
    BASE_LOGIN_ACK = 259,
    BASE_CONNECT_ACK = 514,
    BASE_GET_SYSTEM_INFO_ACK = 523,
    BASE_GET_USER_INFO_ACK = 525,
    BASE_GET_CHANNELLIST_ACK = 541,
    BASE_NOTICE_ACK = 662,
    BASE_URL_LIST_ACK = 673,
    BASE_BOOSTEVENT_INFO_ACK = 676,
    BASE_STEPUP_MODE_INFO_ACK = 691,
    BASE_CHANNELTYPE_CONDITION_ACK = 693,
    AUTH_GET_POINT_CASH_ACK = 1058,
    SERVER_MESSAGE_DISCONNECTIONSUCCESS_ACK = 2546,
    ACK_MAXVAL
};