#include <Network/ServerPacket/PROTOCOL_BASE_CHANNELTYPE_CONDITION_ACK.hpp>
#include <Protocol/Acknowledge.hpp>

PROTOCOL_BASE_CHANNELTYPE_CONDITION_ACK::PROTOCOL_BASE_CHANNELTYPE_CONDITION_ACK()
: AckPacketInterface(eProtocolPacketAck::BASE_BOOSTEVENT_INFO_ACK, 888) {
    //
}

void PROTOCOL_BASE_CHANNELTYPE_CONDITION_ACK::Build() {
    MemorySet(0, 888);
}